---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: "checkout & install"
  image: gvacaliuc/dev:latest
  commands:
    - bash -x .config/bootstrap.sh
    - bash -x .config/dev/install-vim.sh

...
